home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home')
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('update/', views.update_data, name='update'),
    path('progress/<str:task_id>', views.get_progress, name='progress'),
    path('status/<str:task_id>', views.progress_status, name='status'),
]

vkdataanalytics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('report/', include('report.urls')),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

report/models.py
from django.db import models


class VKUser(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)

    def _is_group(self):
        return self.id < 0

    is_group = property(_is_group)


class Post(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    author = models.ForeignKey(VKUser, on_delete=models.CASCADE, related_name='posts')
    date = models.DateTimeField()
    likes = models.PositiveIntegerField(default=0)


class Comment(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(VKUser, on_delete=models.CASCADE, related_name='comments')
    date = models.DateTimeField()
    likes = models.PositiveIntegerField(default=0)

home/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home/home.html', {})

report/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .tasks import process_posts
from celery.result import AsyncResult


def index_view(request):
    return render(request, 'report/index.html', {})


def update_data(request):
    result = process_posts.delay(days=14)
    print(result.backend)
    task_id = result.task_id
    return HttpResponseRedirect(reverse('report:progress', args=[str(task_id)]))


def get_progress(request, task_id):
    result = AsyncResult(id=task_id)
    return render(request, 'report/progress.html', {'state': result.state, 'task_id': task_id})


def progress_status(request, task_id):
    result = AsyncResult(id=task_id)
    return JsonResponse({'state': result.state, 'task_id': task_id})

home/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %}
        Report
        {% endblock %}</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
             <a class="nav-link" href="{% url 'report:index' %}">Report</a>
            </li>
    </ul>

  </div>
</nav>

  <br/>
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}

<a class="btn btn-secondary btn-sm" href="{% url 'report:index' %}" role="button">Show report</a>

{% endblock %}

report/templates/report/index.html
{% extends 'base.html' %}

{% block content %}

<br/>
<iframe width="800" height="650" src="https://datastudio.google.com/embed/reporting/b065b8f8-7872-40b4-bf9c-b7a7d67b4839/page/XCBBC" frameborder="0" style="border:0" allowfullscreen></iframe>
<br/>


<a class="btn btn-secondary btn-sm" href="{% url 'report:update' %}" role="button">Update data</a>

{% endblock %}

report/templates/report/progress.html
  {% extends 'base.html' %}

{% block content %}

  <br/>
<iframe width="800" height="650" src="https://datastudio.google.com/embed/reporting/b065b8f8-7872-40b4-bf9c-b7a7d67b4839/page/XCBBC" frameborder="0" style="border:0" allowfullscreen></iframe>
<br/>

<div id="updated-div" class="badge bg-primary text-wrap" style="width: 10rem; ">
   Status: <p id="updated-p" class="h6" style="text-align:center">{{ state }}</p>
</div>
    <a class="btn btn-secondary btn-sm" href="{% url 'report:index' %}" role="button">Back to report page</a>

    <script type="text/javascript">
    function refresh() {
        $.ajax({
            type: 'GET',
            url: '{% url 'report:status' task_id %}',
            success: function(data) {
                var field = document.getElementById("updated-p")
                field.textContent = data['state']
            }
        });
    }
    setInterval(refresh, 3000);
    $(function(){
        refresh();
    });
    </script>

<br/>
{% endblock %}